# Generated by Django 3.2.5 on 2021-07-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(null=True, verbose_name=False),
        ),
    ]
