# Generated by Django 3.2.4 on 2021-06-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210629_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
